version: "3.9"

services:
  vectorization_service:
    build: .
    image: vectorize_json
    container_name: vectorization_service_container
    environment:
      - ID=gio123
      - SMPC_URL=http://smpc_client:9001
      - ORCHESTRATOR_URL=http://host.docker.internal:5000
      # - ORCHESTRATOR_URL=http://195.251.63.82:5000
      - PRODUCTION_MODE=false  # Set to 'true' to enable Feature Extraction Tool API
      - ENABLE_RESULT_POLLING=true  # Set to 'true' to enable polling for results
      - POLLING_INTERVAL=5          # Seconds between polls
      - POLLING_TIMEOUT=1200         # Max polling time in seconds (20 minutes)
    volumes:
      - ../logs:/app/logs
      - ../results:/app/results
    ports:
      - "5001:5001"
    depends_on:
      - smpc_client

  smpc_client:
    container_name: smpc_client
    image: gpikra/coordinator:v7.0.7.6
    entrypoint: python client.py
    environment:
      - PLAYER_REPO_2=http://195.251.63.193:7102
      - PLAYER_REPO_1=http://195.251.63.193:7101
      - PLAYER_REPO_0=http://195.251.63.193:7100
      - COORDINATOR_URL=http://195.251.63.193:12314
      - ID=gio123
      - REMOTE_SERVICE_URL=https://agoralabsbe.azurewebsites.net
      - PORT=9001
    volumes:
      - ./dataset/docker:/SCALE-MAMBA/dataset
    ports:
      - "9001:9001"
